version: "3.5"
services:

  db:
    image: mysql
    restart: always
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345
      MYSQL_DATABASE: books



  app:
     image: books
     ports:
        - 8081:8080
     environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3308/books?serverTimeZone=UTC

