version: "3.8"
services:

  db:
    image: mysql
    restart: unless-stopped
    build: .
    env_file: ./.env
    ports:
      - $MYSQL_DB_DOCKER_PORT:$MYSQL_DB_LOCAL_PORT

    environment:

      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQL_USER_PASSWORD
      - MYSQL_DATABASE=$DB_NAME




  app:
     image: books
     restart: unless-stopped
     build: .
     ports:
        - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
        - $DEBUG_PORT:$DEBUG_PORT
     environment:
       JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
       SPRING_APPLICATION_JSON: '{
         "spring.datasource.url" : "jdbc:mysql://localhost:$MYSQL_DB_DOCKER_PORT/$MYSQLDB_DATABASE?serverTimeZone=UTC",
         "spring.datasource.username" : "$MYSQLDB_USER",
         "spring.datasource.password" : "MYSQL_USER_PASSWORD",
         "spring.datasource.ddl-auto" : "validate"
       }'
